site_name: Было и было
site_url: https://ioneov.github.io/lifeINIT
theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - content.code.copy
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - footnotes:
      BACKLINK_TEXT: "↩"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/overrides.css